### ISSUE TITLE
Output Broken on Linux

### ISSUE THREAD

**Issue by inferno771** [tehguy/EzReplace#4]
frig1d@pyre:~/ezreplace$ java -jar EzReplace-2.1.3.4.jar nogui                     
Reading locations to memory...Done
Reading asset CSVs to memory...Done
CLI requested...
[B]arcode or [S]erial?: B

Enter barcode/serial: 419999

Enter location code: 003

Enter device type: Test

Enter tech notes: Test

Enter replacement request: Test
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
        at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
        at function.Functions.copyTextToClipboard(Functions.java:19)
        at function.Functions.generateFinalString(Functions.java:63)
        at layout.CLIForm.nogui(CLIForm.java:19)
        at Runner.main(Runner.java:27)

**Comment by inferno771** [comment]
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at sun.awt.HeadlessToolkit.getSystemClipboard(HeadlessToolkit.java:309)
        at function.Functions.copyTextToClipboard(Functions.java:19)
        at function.Functions.generateFinalString(Functions.java:63)
        at layout.CLIForm.nogui(CLIForm.java:19)
        at Runner.main(Runner.java:27)

**Comment by JTM-rootstorm** [comment]
Note to self: make clipboard toggle-able
